spring:
  datasource:
    url: jdbc:h2:mem:stackoverclone
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console # http://localhost:8080/h2-console

  # Colored output in console
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS

security:
  oauth2:
    resource:
      filter-order: 3
  signing-key: MaYzkSjmkzPC57L
  security-realm: Stackoverclone Realm
  jwt:
    client-id: jwtclientid
    client-secret: "{noop}XY7kmzoNzl100"
    grant-types: password,refresh_token
    scope-read: read
    scope-write: write
    resource-ids: jwtresourceid