spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stackoverclone
    driverClassName: com.mysql.cj.jdbc.Driver
    username: sa
    password: 11
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console # http://localhost:8080/h2-console

  # Colored output in console
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS

security:
  oauth2:
    resource:
      filter-order: 3
  signing-key: MaYzkSjmkzPC57L
  security-realm: Stackoverclone Realm
  jwt:
    client-id: jwtclientid
    client-secret: "{noop}XY7kmzoNzl100"
    grant-types: password,refresh_token
    scope-read: read
    scope-write: write
    resource-ids: jwtresourceid

liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.yaml
